#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "this hook is running 🔥🔥🔥🔥🔥🔥" 

branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
if [[ "$branch" == "master" ]] || [[ "$branch" == "development" ]] || [[ "$branch" == "qa" ]] 
then
    echo "cannot commit to major branches" 
    exit 1 
else 
    echo "Running code tests... 🔥🔥🔥🔥" 
    npm run lint
fi